### PR TITLE
Add jbuilder

### PR DESCRIPTION
**Pull request by shootingfly**

### CODE REVIEW

**Comment by jeromegn** [comment]
Any idea why CI would be broken? I haven't worked with Crystal in forever.

**Comment by shootingfly** [comment]
@jeromegn I made a PR  in liquid to fix the error.

**Comment by shootingfly** [comment]
@jeromegn I have fixed the error in **liquid.cr**, please try again.

**Comment by jeromegn** [comment]
I'm not sure why, but Travis is not picking up these latest changes in liquid.cr. I was going to force the version to be at least 0.3.2 to fix master, but the git tag has not been pushed yet on the liquid repo.

**Comment by shootingfly** [comment]
The author haven't git tag yet. So can force to use the master branch?

**Comment by jeromegn** [comment]
That's what I thought it would do since I'm not specifying a version or a
commit in the shards.yml. I thought there might have been a cache on
travis, but I get the same locally.

**Comment by shootingfly** [comment]
The author has tag it. Please try again.

**Pull request merged**
