### PR TITLE
`embed_ecr` is now deprecated. Using `ECR.embed` instead.

### PR DESCRIPTION
**Pull request by f**
Related to: https://github.com/manastech/crystal/blob/master/src/ecr/macros.cr#L3

### CODE REVIEW

**Comment by f** [comment]
Travis is failing b/c not including newest Crystal changes.

**Comment by jeromegn** [comment]
I was thinking of waiting until it's 100% deprecated. There has not be a release of Crystal with this change yet and the next release will also work with the old way. I fear of breaking people's code (Kemal includes this library as a dependency) by merging this too soon.

Next release of Crystal might be a good time to do it, or maybe the one after that when they remove `embed_ecr`. Entirely.

Feel free to leave this here and opened and we can revisit when that happens? What do you think? :)

(also, I merged another PR that makes this one unmergeable)

**Comment by f** [comment]
I think you're right. We should wait.

**Comment by enderahmetyurt** [comment]
:+1:

**Comment by drujensen** [comment]
question:  Usually I keep master branch as the latest source and then maintain versions so that people can continue to use older ones.  I find this deprecation warning annoying.  What is your recommendation?  Should I fork?

**Comment by jeromegn** [comment]
@drujensen given that I have tagged this repo, we can probably merge this in (with minor mods to make it up to date with master) but not tag it yet. I imagine `shards {install,update}` will not pull on untagged commits if there are tags on a repo.

Give me a little while.

**Comment by drujensen** [comment]
Thanks @jeromegn!  Really appreciate the work.

**Comment by jeromegn** [comment]
@drujensen sure!

Ok done, this has been merged in master.

**Pull request closed without merging**
