### PR TITLE
Added Mustache adapter

### PR DESCRIPTION
**Pull request by makenowjust**
Added Mustache adapter (using crustache) and add maintainer section to the table of supported language.

kilt is great, however I am fascinated by no-adapter idea. I will continue development [TILT](https://github.com/MakeNowJust/tilt). (And, one problem, I really love the name "TILT". It is pretty cute;)

### CODE REVIEW

**Comment by jeromegn** [comment]
Ah, nice! Thanks.

@waterlink That makes me wonder... maybe we could add those various `kilt/slang`, `kilt/crustache` directly in kilt. People could just do something like:

``` crystal
require "kilt"
require "slang"
require "kilt/slang"
```

I guess this comes back to how things were before, except those various "adapters" would just be directly in the library.

**Comment by waterlink** [comment]
Yeah that is totally nice. Since it is still decoupled enough for me to register my own private adapter.

**Comment by jeromegn** [comment]
Thanks @MakeNowJust, I modified it slightly and merged it in master :)

Now we have both the ability to register adapters and built-in adapters (which can be overridden if something is wrong.)

**Comment by waterlink** [comment]
:+1:

**Pull request merged**
